### ISSUE TITLE
segmented control is not expand during landscape mode. 

### ISSUE THREAD

**Issue by andrewlim7** [VeinGuo/VGSegment#1]
I did set constraints for the segmented control in UIView storyboard. However when I tried to change landscape mode it tends to stick with current view.frame.size.width.

**Comment by VeinGuo** [comment]
@andrewlim7 fix ab9257f.   pod update v1.0.2

**Comment by andrewlim7** [comment]
Hi,

[image1.JPG]

I'm sorry, I'm new to iOS. May I know how to expand it? I did set auto layout to 8 from the right. It doesn't work on my iPhone as well. Do I have to set up anything?

Sincerely,
Andrew

On Sep 6, 2017, at 7:12 PM, WenRong <notifications@github.com<mailto:notifications@github.com>> wrote:


@andrewlim7<https://github.com/andrewlim7> fix ab9257f<https://github.com/VeinGuo/VGSegment/commit/ab9257fe5d2bd03bf6148d2de004ffb2d5b5c2de>. pod update v1.0.2

**Comment by andrewlim7** [comment]
Hi, 

Sorry for troubling you, here are my codes for you to better understanding.




Segment = segment : VGSegment
VgSegment = UIView from storyboard. 
ConfigureSegment = VGSegmentConfiguration() 

Sincerely,
Andrew
